Repository cloud-native-toolkit/iascable, pull requests merged in 2022-08, with the labels that each got.

#161 Fixes install.sh script on Ubuntu
  install.sh
Labels: bug, patch

#176 Handles relocated modules
  .github/workflows/release.yaml
  README.md
  package.json
  src/models/catalog.model.spec.ts
  src/models/catalog.model.ts
  src/models/module.model.ts
  src/moduleIdAliases.yaml
  src/services/catalog-loader/catalog-loader.impl.ts
  src/services/module-selector/selected-modules.resolver.spec.ts
  src/services/module-selector/selected-modules.resolver.ts
  test/catalog.yaml
Labels: minor, feature

#177 Fixes typo in readme
  README.md
Labels: bug, patch

#178 Adds support for multi-architecture build
  .github/workflows/asset-publish.yaml
  .github/workflows/release.yaml
  .github/workflows/verify-pr.yaml
  install.sh
  package.json
Labels: patch, chore

#179 Updates workflow to test multi-arch build
  .github/workflows/verify-pr.yaml
  package.json
Labels: bug, patch

#182 Fixes issue in chmodRecursive call
  __mocks__/fs.js
  package-lock.json
  src/commands/iascable-build.ts
  src/util/file-util.spec.ts
  src/util/file-util.ts
Labels: bug, patch

#183 Fixes issues installing back-level versions of cli
  .github/workflows/asset-publish.yaml
  README.md
  install.sh
Labels: bug, patch

#184 updates for launch.sh from automation-solutions
  scripts/launch.sh
Labels: bug, minor

#186 Updates launch script generated in output
  scripts/launch.sh
  src/commands/iascable-build.ts
  src/commands/scripts/apply-script.ts
  src/commands/scripts/destroy-script.ts
  src/commands/scripts/index.ts
  src/commands/scripts/launch-script.ts
Labels: bug, patch

#187 Allows for multiple catalogs to be provided during build
  README.md
  examples/catalog-urls.yaml
  src/commands/iascable-build.ts
  src/commands/inputs/iascable.input.ts
  src/models/catalog.model.spec.ts
  src/services/catalog-loader/catalog-loader.api.ts
  src/services/catalog-loader/catalog-loader.impl.ts
  src/services/iascable.api.ts
  src/services/iascable.impl.ts
  test/catalog.yaml
Labels: minor, feature
