Repository cloud-native-toolkit/iascable, pull requests merged in 2022-10, with the labels that each got.

#226 keep leading slash in catalog file path
  src/services/catalog-loader/catalog-loader.impl.ts
Labels: bug, patch

#227 Updates apply script to handle extra variables added to variables.yaml
  scripts/apply.sh
Labels: bug, patch

#228 Cleans up error message when file cannot be written
  src/commands/iascable-build.ts
Labels: bug, patch

#229 Adds support for module metadata as catalog input
  src/models/catalog.model.ts
  src/models/crd.model.ts
  src/models/module.model.ts
  src/services/catalog-loader/catalog-loader.impl.ts
  src/services/module-selector/module-selector.impl.spec.ts
  src/services/module-selector/selected-modules.resolver.spec.ts
  test/catalog.yaml
Labels: minor, feature

#232 Updates catalogUrls to include base catalog by default
  src/commands/iascable-build.ts
  src/commands/iascable-docs.ts
  src/commands/support/middleware.ts
Labels: bug, patch

#233 Adds command to generate catalog
  examples/catalog-urls.yaml
  src/commands/iascable-catalog.ts
  src/commands/iascable-metadata.ts
  src/commands/inputs/iascable.input.ts
  src/models/catalog.model.spec.ts
  src/models/catalog.model.ts
  src/models/module.model.ts
  src/models/stages.model.ts
  src/moduleIdAliases.yaml
  src/services/catalog-builder/catalog-builder-service.ts
  src/services/catalog-builder/catalog-builder.api.ts
  src/services/catalog-builder/index.ts
  src/services/catalog-loader/catalog-loader.impl.ts
  src/services/module-documentation/module-documentation.api.ts
  src/services/module-documentation/module-documentation.ts
  src/services/module-selector/module-selector.api.ts
  src/services/module-selector/module-selector.impl.spec.ts
  src/services/module-selector/module-selector.impl.ts
  src/services/module-selector/selected-modules.resolver.spec.ts
  src/services/terraform-builder/terraform-buiilder.impl.spec.ts
  src/services/terraform-builder/terraform-builder.api.ts
  src/services/terraform-builder/terraform-builder.new.ts
  src/util/array-util/flatten.ts
  src/util/array-util/index.ts
  src/util/file-util.ts
  test/catalogv1.yaml
Labels: minor, feature

#237 Includes output.tf in generated terraform
  src/models/bill-of-material.model.ts
  src/models/module.model.ts
  src/models/stages.model.ts
  src/models/variables.model.ts
  src/services/terraform-builder/terraform-builder.new.ts
Labels: minor, feature

#243 Update to current launch script for cli-tools update
  scripts/launch.sh
Labels: bug, patch

#244 Adds logic to generate metadata using local file
  package-lock.json
  package.json
  src/commands/iascable-catalog.ts
  src/commands/iascable-metadata.ts
  src/commands/inputs/iascable.input.ts
  src/services/module-metadata-service/module-metadata-service.ts
  src/services/module-metadata-service/module-metadata.api.ts
  src/services/module-selector/module-selector.impl.ts
  src/util/file-util.spec.ts
  src/util/question-builder/index.ts
  src/util/question-builder/question-builder.api.ts
  src/util/question-builder/question-builder.impl.ts
  src/util/question-builder/question-builder.spec.ts
  src/util/terraform/terraform-file.ts
  src/util/yaml-file/yaml-file.ts
Labels: minor, feature

#245 Fixes catalog logic to ensure custom modules override base catalog
  src/models/stages.model.ts
  src/services/catalog-loader/catalog-loader.impl.ts
Labels: bug, patch

#251 Adds module aliases if module overridden in catalog
  src/services/catalog-loader/catalog-loader.impl.ts
Labels: bug, patch

#254 Updates verify workflow to trigger on prs on all branches
  .github/workflows/verify-pr.yaml
Labels: patch, chore

#256 Updates tag value for npm-publish workflow
  .github/workflows/npm-publish.yaml
  README.md
Labels: bug, patch

#260 Fixes version numbers created by release version workflow
  .github/workflows/release.yaml
  README.md
Labels: patch, chore
