Repository cloud-native-toolkit/iascable, pull requests merged in 2022-09, with the labels that each got.

#207 Adds docs command to generate the readme for a module
  src/commands/iascable-docs.ts
  src/commands/inputs/iascable.input.ts
  src/errors/module-not-found.error.ts
  src/models/index.ts
  src/models/module-doc.model.ts
  src/models/module.model.ts
  src/services/iascable.api.ts
  src/services/iascable.impl.ts
  src/services/module-documentation/index.ts
  src/services/module-documentation/module-documentation.api.ts
  src/services/module-documentation/module-documentation.ts
Labels: minor, feature

#208 Updates README with some developer documentation
  README.md
Labels: patch, chore

#209 Updates documentation generation process
  src/models/module.model.ts
  src/models/stages.model.ts
  src/services/iascable.impl.ts
  src/services/module-documentation/module-documentation.api.ts
  src/services/module-documentation/module-documentation.ts
  src/util/iascable-version.ts
Labels: minor, feature

#214 Fixes error handling when dealing with multiple BOMs
  package-lock.json
  package.json
  src/commands/iascable-build.ts
  src/errors/stage-not-found.error.ts
  src/models/variables.model.ts
Labels: bug, patch

#217 handle complex types in first apply run
  scripts/apply.sh
Labels: bug, patch

#218 Adds metadata command
  package-lock.json
  package.json
  src/commands/iascable-metadata.ts
  src/commands/inputs/iascable.input.ts
  src/models/bill-of-material.model.ts
  src/models/catalog.model.ts
  src/models/module.model.ts
  src/models/stages.model.ts
  src/models/variables.model.ts
  src/models/version-matcher.ts
  src/services/bill-of-material-builder/bill-of-material-builder.ts
  src/services/dependency-graph/dependency-graph.impl.ts
  src/services/iascable.impl.ts
  src/services/module-metadata-service/errors.ts
  src/services/module-metadata-service/index.ts
  src/services/module-metadata-service/module-metadata-service.ts
  src/services/module-metadata-service/module-metadata.api.ts
  src/services/module-selector/module-selector.impl.ts
  src/services/module-selector/selected-modules.model.ts
  src/services/module-selector/selected-modules.resolver.ts
  src/services/terraform-builder/terraform-buiilder.impl.spec.ts
  src/services/terraform-builder/terraform-builder.new.ts
  src/util/array-util/array-util.ts
  src/util/array-util/difference.ts
  src/util/array-util/first.ts
  src/util/array-util/includes-all.ts
  src/util/array-util/index.ts
  src/util/file-util.spec.ts
  src/util/terraform/terraform-file.ts
  src/util/version-resolver/version-resolver.spec.ts
  src/util/yaml-file/yaml-file.ts
Labels: minor, feature

#222 Fixes error message during build
  src/commands/iascable-build.ts
Labels: bug, patch

#221 Handles version number for unreleased module
  src/commands/iascable-metadata.ts
Labels: bug, patch
